name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry 
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myImage:testTag
    - name: Push the tagged Docker image
      run: docker push myImage:testTag
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag myImage:latest
    - name: Push the latest Docker image
      run: docker push myImage:latest
