name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Push the tagged Docker image
      run: docker push my-image-name:$(date +%s)
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: Push the latest Docker image
      run: docker push my-image-name:latest
